site_name: kirk-ai
site_description: "kirk-ai — CLI for interacting with Ollama AI models"
site_author: The Aid Guild

# Logo and favicon
logo: assets/images/logo.svg
favicon: assets/images/logo.svg

# Edit URI (optional) — enable 'Edit on GitHub' links
edit_uri: blob/main/

site_url: https://theaidguild.github.io/kirk-ai/

docs_dir: docs_src
site_dir: site

theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: cyan
  features:
    - navigation.instant
    - navigation.indexes
    - search.highlight
    - navigation.tabs
    - header.autohide
    - content.code.copy
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - git-revision-date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/theaidguild/kirk-ai

extra_css:
  - assets/stylesheets/overrides.css

extra_javascript:
  - assets/javascripts/copy-page.js

nav:
  - Get Started:
      - Welcome: index.md
      - Installation: installation.md
      - Quickstart: usage.md
  - Servers:
      - Overview: architecture.md
      - Core Components: commands.md
      - Advanced Features: 
          - Contributing: contributing.md
  - Clients:
      - Overview: commands.md
  - Integrations:
      - Overview: installation.md
