site_name: kirk-ai
site_description: "kirk-ai — CLI for interacting with Ollama AI models"
site_author: The Aid Guild

# Edit URI (optional) — enable 'Edit on GitHub' links
edit_uri: blob/main/

site_url: https://theaidguild.github.io/kirk-ai/

docs_dir: docs_src
site_dir: site

theme:
  name: material
  # logo and favicon removed per request
  palette:
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.indexes
    - search.highlight
    - navigation.tabs
    - header.autohide
    - content.code.copy
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/theaidguild/kirk-ai

extra_css:
  - assets/stylesheets/overrides.css

nav:
  - Get Started:
      - Welcome: index.md
      - TPUSA AI: tpusa_ai.md
      - Installation: installation.md
      - Quickstart: usage.md
  - Servers:
      - Overview: architecture.md
      - Core Components: commands.md
      - Advanced Features:
          - Contributing: contributing.md
  - Clients:
      - Overview: commands.md
  - Integrations:
      - Overview: installation.md
