site_name: kirk-ai
site_description: "CLI for interacting with Ollama AI models"
repo_name: theaidguild/kirk-ai
repo_url: https://github.com/theaidguild/kirk-ai

docs_dir: docs_src
site_dir: site

theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: cyan
  features:
    - navigation.instant
    - navigation.indexes
    - search.highlight
    - navigation.tabs
    - header.autohide
    - content.code.copy
  language: en
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/theaidguild/kirk-ai

extra_css:
  - assets/stylesheets/overrides.css

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Commands: commands.md
  - Architecture: architecture.md
  - Contributing: contributing.md
