name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]

# Ensure the workflow has permission to push if using actions that write branches
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Show workspace (diagnostic)
        run: |
          echo "Workspace: $(pwd)"
          echo "Listing root files:" && ls -la
          echo "Checking docs/ presence..."
          if [ -d "docs" ]; then
            echo "docs/ exists. Listing docs/:" && ls -la docs
          else
            echo "ERROR: docs/ directory not found in repository workspace." && exit 1
          fi

      - name: Ensure .nojekyll exists inside docs (will be copied to root of published branch)
        run: |
          if [ ! -f docs/.nojekyll ]; then
            echo "Creating docs/.nojekyll to disable Jekyll on the published branch";
            touch docs/.nojekyll;
            git config --global user.email "actions@github.com";
            git config --global user.name "GitHub Actions";
            git add docs/.nojekyll;
            git commit -m "chore: add .nojekyll to docs for Pages" || echo "No changes to commit";
          else
            echo "docs/.nojekyll already present";
          fi

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          nojekyll: true
          # Optional: set the branch name (defaults to gh-pages)
          # publish_branch: gh-pages

# Note: if your organization or repository settings restrict the GITHUB_TOKEN's write permissions, the action may still fail with "Write access to repository not granted." In that case either:
# - Adjust repository or organization Actions permissions to allow write access for workflows, or
# - Create a personal access token with repo:status, repo_deployment, public_repo, repo:invite and add it as a secret (e.g. GH_PAGES_PAT) and pass it as `personal_token: ${{ secrets.GH_PAGES_PAT }}` to the peaceiris action.
